spring:
  data:
    mongodb:
      port: 0
      database: library

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean" # Если используется Shell, чтобы не было конфликтов
  change-logs-scan-package:
    - ru.otus.mongock.changelog

logging:
  level:
    root: error
